### ISSUE TITLE
@import '~weui/dist/style/weui.css';

### ISSUE THREAD

**Issue by pangshangggg** [cipchk/ngx-weui#88]
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./sr
c/styles.scss
Module build failed: Error: Can't resolve 'weui/dist/style/weui.css' in 'E:\qunyao_server\qunyao_server\trunk\cjsr-web\src'
    at onError (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\Resolver.js:61:15)
    at loggingCallbackWrapper (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\createInnerCallback.js:
31:19)
    at runAfter (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\createInnerCallback.js:
31:19)
    at next (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\tapable\lib\Tapable.js:252:11)
    at E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\createInnerCallback.js:
31:19)
    at runAfter (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\createInnerCallback.js:
31:19)
    at next (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\tapable\lib\Tapable.js:252:11)
    at innerCallback (E:\qunyao_server\qunyao_server\trunk\cjsr-web\node_modules\enhanced-resolve\lib\Resolver.js:144:11)

**Comment by cipchk** [comment]
确保安装

```bash
npm i --save weui
```

我也遇到过无法使用上面命令安装，可以直接在 `package.json` 里面加入 `weui` 的配置，然后再运行：`npm i`

**Comment by cipchk** [comment]
我会在下一版本加入 `weui` 的强制依赖
